name: app_movil_coffe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
